name: Push main to public repo on release

on:
  release:
    types: [published]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the tag from the release
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0

      - name: Setup Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push the tag to the public repo
        env:
          TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
        run: |
          git remote add public https://x-access-token:${TOKEN}@github.com/UMCU-Digital-Health/discharge-documentation-generator
          git push public ${{ github.event.release.tag_name }}:refs/tags/${{ github.event.release.tag_name }} --force
